[package]
name = "qrpc"
version = "0.1.0"
edition = "2021"

[lib]
crate-type=["cdylib"]

[dependencies]
bytes = "1"
kdbplus={version="^0.3.7", features=["api"]}
once_cell="1"
prost="^0.9"
prost-types="^0.9"
prost-reflect="^0.5.5"
tonic="^0.6"

[build-dependencies]
tonic-build="^0.6"
